apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../apps/flask-app/deployment.yaml
- ../../apps/microservice-1/deployment.yaml
- ../../apps/microservice-2/deployment.yaml

namespace: staging

commonLabels:
  environment: staging

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flask-app
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: flask-app
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: user-service
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: user-service
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: product-service
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: product-service
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

configMapGenerator:
- name: staging-config
  literals:
  - LOG_LEVEL=INFO
  - DEBUG=false

secretGenerator:
- name: staging-secrets
  literals:
  - secret-key=staging-secret-key-456
