apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-pipeline-project
  namespace: argocd
spec:
  description: DevOps Pipeline Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: PersistentVolumeClaim
  - group: networking.k8s.io
    kind: Ingress
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: networking.k8s.io
    kind: '*'
  roles:
  - name: admin
    description: Admin role
    policies:
    - p, proj:devops-pipeline-project:admin, applications, *, devops-pipeline-project/*, allow
    - p, proj:devops-pipeline-project:admin, repositories, *, *, allow
    groups:
    - argocd-admins
  - name: developer
    description: Developer role
    policies:
    - p, proj:devops-pipeline-project:developer, applications, get, devops-pipeline-project/*, allow
    - p, proj:devops-pipeline-project:developer, applications, sync, devops-pipeline-project/dev-*, allow
    groups:
    - argocd-developers
