apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: product-secrets
              key: secret-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  secret-key: ZGV2LXNlY3JldC1rZXk= # base64 encoded "dev-secret-key"
