site_name: DevOps Pipeline Documentation
site_description: Unified Production-Ready DevOps Pipeline Documentation
site_url: https://your-org.github.io/devops-pipeline
repo_url: https://github.com/your-org/devops-pipeline
repo_name: your-org/devops-pipeline

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Quick Start: quick-start.md
  - Runbooks:
    - Installation: runbooks/installation.md
    - CI/CD Pipeline: runbooks/cicd-pipeline.md
    - GitOps Sync: runbooks/gitops-sync.md
    - Blue-Green Switch: runbooks/blue-green-switch.md
    - DR Restore: runbooks/dr-restore.md
  - Security: security.md
  - Monitoring: monitoring.md
  - Troubleshooting: troubleshooting.md
  - API Reference: api-reference.md
